name: Docker Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-project:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    env:
      GITHUB_REGISTRY: ghcr.io
      ALIYUN_REGISTRY: registry.cn-hangzhou.aliyuncs.com
      ALIYUN_NAMESPACE: ${{ vars.ALIYUN_NAMESPACE }}
      DOCKERHUB_NAMESPACE: ${{ vars.DOCKERHUB_NAMESPACE }}

    steps:
      - name: üå± Checkout repository
        uses: actions/checkout@v4

      - name: ‚öôÔ∏è Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: üîß Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: üê≥ Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: üê≥ Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: üê≥ Login to Aliyun Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_TOKEN }}

      - name: üì¶ Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_NAMESPACE }}/orion-visor-agent
            ${{ env.GITHUB_REGISTRY }}/${{ github.repository_owner }}/orion-visor-agent
            ${{ env.ALIYUN_REGISTRY }}/${{ env.ALIYUN_NAMESPACE }}/orion-visor-agent
          tags: |
            type=semver,pattern={{version}}         
            type=semver,pattern={{major}}.{{minor}} 
            type=semver,pattern={{major}}           

      - name: üõ†Ô∏è Build and push Docker image for orion-visor-agent
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ${{ env.DOCKERHUB_NAMESPACE }}/orion-visor-agent:${{ steps.meta.outputs.version }}
            ${{ env.DOCKERHUB_NAMESPACE }}/orion-visor-agent:latest
            ${{ env.GITHUB_REGISTRY }}/${{ github.repository_owner }}/orion-visor-agent:${{ steps.meta.outputs.version }}
            ${{ env.GITHUB_REGISTRY }}/${{ github.repository_owner }}/orion-visor-agent:latest
            ${{ env.ALIYUN_REGISTRY }}/${{ env.ALIYUN_NAMESPACE }}/orion-visor-agent:${{ steps.meta.outputs.version }}
            ${{ env.ALIYUN_REGISTRY }}/${{ env.ALIYUN_NAMESPACE }}/orion-visor-agent:latest
